sync:
  defaults:
    ignore:
      vcs: true
      paths:
        - ".DS_Store"
        - "._*"
        - "*~"
        - "*.sw[a-p]"
        - "env"
        - "*.bak"
        - "*.log"
        - "projectile-bookmarks.eld"
    symlink:
        mode: "ignore"
